version: '3'

services:

  mysql:
    image: mysql:8.0
    container_name: ${DBCONTAINER}
    environment:
      - MYSQL_DATABASE=${DBNAME}
      - MYSQL_ROOT_PASSWORD=${DBPASS}
      - MYSQL_DEFAULT_AUTHENTICATION_PLUGIN=mysql_native_password
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql:/var/lib/mysql
    ports:
        - ${DBPORT}:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  www:
    build: .
    container_name: ${PSCONTAINER}
    volumes :
      - ./www:/var/www/html:rw
    restart: always
    ports:
      - ${PSPORT}:80
    links:
      - mysql:${DBCONTAINER}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${MACONTAINER}
    links:
      - mysql
    environment:
      PMA_HOST: ${DBCONTAINER}
      PMA_PORT: ${DBPORT}
    restart: always
    ports:
      - ${MAPORT}:80

volumes:
  mysql:
